all: doc pseudo-clean

doc:
	pdflatex "Homework 1 Solution.tex" \ pdflatex "Homework 1 Solution.tex"

clean: pseudo-clean
	rm -f "Homework 1 Solution.pdf"

pseudo-clean:
	rm -f "Homework 1 Solution.aux" "Homework 1 Solution.log" "Homework 1 Solution.toc"
